palette='zilq'
format = '''
[┌](fg:lines)[░▒▓](fg:#606060)$directory$git_branch[](fg:#242424)$fill[](fg:#242424)$golang$nodejs$java$username$hostname$time
[└](fg:lines)$character
'''
add_newline = true

[golang]
format = '[ \[golang \($version\)\] ](bg:#242424)'

[hostname]
format = '[$hostname](bold red)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#606060"
format = '[](fg:#4c4c4c bg:#242424)[[󱑂 $time](fg:#b0b8c5 bg:#4c4c4c)]($style)'

[character]
format='[ ](fg:#606060)'

[directory]
truncate_to_repo = false
format='[󰉋 $path]($style)[](fg:#4c4c4c bg:#242424)'
home_symbol='~'
style='bg:#4c4c4c fg:#b0b8c5'
read_only='RO'
truncation_length = 3

[git_branch]
format='[  $branch(:$remote_branch)](bg:#242424)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[status]
format='[$status]($style)'
disabled=false

[fill]
symbol='─'
style='fg:#1a1a1a'

[java]
format = '[ \[java \($version\)\] ](bg:#242424)'

[nodejs]
format = '[ \[nodejs \($version\)\] ](bg:#242424)'

[palettes.zilq]
lines='#565656'
char='#c2c2c2'
bracket='#565656'
dir='#70b900'
git='#c68a01'
ver_key='#c68a01'
ver_sep='#c2c2c2'
ver_val='#858585'
